export const PROFILE_UPDATE_DETAILS = 'PROFILE_UPDATE_DETAILS';
export const PROFILE_UPDATE_AVATAR = 'PROFILE_UPDATE_AVATAR';
export const PROFILE_FETCHING_STARTED = 'PROFILE_FETCHING_STARTED';
export const PROFILE_FETCHING_FAILED = 'PROFILE_FETCHING_FAILED';
export const PROFILE_UPLOADING_FAILED = 'PROFILE_UPLOADING_FAILED';
export const PROFILE_AVATAR_UPLOADING_STARTED = 'PROFILE_AVATAR_UPLOADING_STARTED';
export const PROFILE_AVATAR_UPLOADING_FAILED = 'PROFILE_AVATAR_UPLOADING_FAILED';
export const PROFILE_AVATAR_FETCHING_STARTED = 'PROFILE_AVATAR_FETCHING_STARTED';
export const PROFILE_AVATAR_FETCHING_FAILED = 'PROFILE_AVATAR_FETCHING_FAILED';

export const SHARED_RECEIVE_TOKEN = 'SHARED_RECEIVE_TOKEN';
export const SHARED_INVALIDATE_TOKEN = 'SHARED_INVALIDATE_TOKEN';
export const SHARED_AUTHENTICATION_STARTED = 'SHARED_AUTHENTICATION_STARTED';
export const SHARED_REGISTRATION_STARTED = 'SHARED_REGISTRATION_STARTED';
export const SHARED_AUTHENTICATION_FAILED = 'SHARED_AUTHENTICATION_FAILED';
export const SHARED_REGISTRATION_FAILED = 'SHARED_REGISTRATION_FAILED';
export const SHARED_DISMISS_ERROR = 'SHARED_DISMISS_ERROR';
export const LOGGED_USER = 'LOGGED_USER';
export const APP_DATA = 'APP_DATA';
export const START_FETCHING_APP_DATA = 'START_FETCHING_DATA';

export const MESSAGE_CREATE = 'MESSAGE_CREATE';
export const MESSAGE_FETCH = 'MESSAGE_FETCH';
export const MESSAGE_DELETE = 'MESSAGE_DELETE';
export const MESSAGE_UPVOTE = 'MESSAGE_UPVOTE';
export const MESSAGE_DOWNVOTE = 'MESSAGE_DOWNVOTE';

export const CHANNEL_CREATE = 'CHANNEL_CREATE';
export const CHANNEL_DELETE = 'CHANNEL_DELETE';
export const CHANNEL_UPDATE_NAME = 'CHANNEL_UPDATE_NAME';
export const CHANNEL_INVATE_USER = 'CHANNEL_INVATE_USER';
export const CHANNEL_FETCH = 'CHANNEL_FETCH';
